In [1]:
folder = "../data_deep_learning/Bible_fr.txt"


In [2]:
with open(folder, "r") as f:
    lines = f.readlines()

In [3]:
len(lines)

41899

In [4]:
lines[41898]

'\n'

In [5]:
lines[45]

'L’Éternel Dieu prit l’homme, et le plaça dans le jardin d’Éden pour le cultiver et pour le garder.\n'

### Nettoyage du corpus

In [6]:
corpus = []

for line in lines:
    line = line.split("\n")[0]
    line = line.lower()
    if line:
        corpus.append(line)
    

In [7]:
len(corpus)

31055

In [8]:
corpus = corpus[:7000]

### Tokenisation

In [9]:
corpus[45]

'l’éternel dieu prit l’homme, et le plaça dans le jardin d’éden pour le cultiver et pour le garder.'

In [10]:
from tensorflow.keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer()

2024-02-07 16:31:37.872279: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-02-07 16:31:43.839022: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2024-02-07 16:31:43.839089: I tensorflow/compiler/xla/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2024-02-07 16:31:59.895571: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
2024-

In [11]:
len(corpus)

7000

In [12]:
tokenizer.fit_on_texts(corpus)

In [15]:
len(tokenizer.word_index)

9420

In [16]:
seq = tokenizer.texts_to_sequences([corpus[3]])[0]

In [17]:
seq

[27, 279, 10, 4, 1840, 78, 1102, 1, 27, 2660, 4, 1840, 2284, 5, 1542]

In [20]:
for i in range(1, len(seq)):
    print(seq[:i+1])

[27, 279]
[27, 279, 10]
[27, 279, 10, 4]
[27, 279, 10, 4, 1840]
[27, 279, 10, 4, 1840, 78]
[27, 279, 10, 4, 1840, 78, 1102]
[27, 279, 10, 4, 1840, 78, 1102, 1]
[27, 279, 10, 4, 1840, 78, 1102, 1, 27]
[27, 279, 10, 4, 1840, 78, 1102, 1, 27, 2660]
[27, 279, 10, 4, 1840, 78, 1102, 1, 27, 2660, 4]
[27, 279, 10, 4, 1840, 78, 1102, 1, 27, 2660, 4, 1840]
[27, 279, 10, 4, 1840, 78, 1102, 1, 27, 2660, 4, 1840, 2284]
[27, 279, 10, 4, 1840, 78, 1102, 1, 27, 2660, 4, 1840, 2284, 5]
[27, 279, 10, 4, 1840, 78, 1102, 1, 27, 2660, 4, 1840, 2284, 5, 1542]


In [13]:
sequences = tokenizer.texts_to_sequences(corpus)

In [14]:
input_sequences = []

for seq in sequences:
    for i in range(1, len(seq)):
        data_line = seq[:i+1]
        input_sequences.append(data_line)

In [15]:
len(input_sequences)

163770

In [16]:
max([len(x) for x in input_sequences])

66

In [21]:
input_sequences[7: 12] # [7: 12] 7 à 12

[[29, 2046, 27, 1541, 5, 549, 1, 4, 91],
 [4, 91],
 [4, 91, 78],
 [4, 91, 78, 5561],
 [4, 91, 78, 5561, 1]]

In [17]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [24]:
input_sequences = pad_sequences(input_sequences, 
              padding="pre", 
              maxlen=66)

In [25]:
input_sequences[7: 12]

array([[   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,   29, 2046,   27, 1541,    5,  549,    1,    4,   91],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    4,   91],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0

### Creating x_train et y_train

In [26]:
input_sequences.shape

(163770, 66)

In [27]:
x_train = input_sequences[:, :-1]  # numpy array
y_train = input_sequences[:, -1]  # numpy array

In [40]:
x_train.shape, y_train.shape

((163770, 65), (163770,))

In [39]:
x_train

array([[   0,    0,    0, ...,    0,    0,   29],
       [   0,    0,    0, ...,    0,   29, 2046],
       [   0,    0,    0, ...,   29, 2046,   27],
       ...,
       [   0,    0,    0, ..., 1372,   41,   24],
       [   0,    0,    0, ...,   41,   24,   10],
       [   0,    0,    0, ...,   24,   10,  475]], dtype=int32)

In [36]:
y_train

array([2046,   27, 1541, ...,   10,  475,   11], dtype=int32)

In [41]:
import tensorflow as tf

In [42]:
tf.keras.utils.to_categorical([4, 2, 1])

array([[0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0.]], dtype=float32)

In [43]:
# One Hot Encoding
y_train = tf.keras.utils.to_categorical(y_train)

In [44]:
y_train.shape

(163770, 9421)

### Modeling

In [45]:
import numpy as np

In [46]:
vocab_size = 9421
embedding_dim = np.power(vocab_size, 1/4)

9.851996546912787

In [48]:
embedding_dim = 10

In [49]:
model = tf.keras.models.Sequential(
    [
        tf.keras.layers.Embedding(vocab_size, embedding_dim),
        tf.keras.layers.Bidirectional(tf.keras.layers.LSTM(16)), 
        tf.keras.layers.Dense(vocab_size, activation='softmax') # Une classification sur chacun des mots de vocab_size
        # Un peu comme sur le Fashion MNIST ou on devait prédire 9classes(labels)
    ]
)

model.compile(optimizer="adam", loss="categorical_crossentropy", metrics=["accuracy"])

In [50]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, None, 10)          94210     
                                                                 
 bidirectional_1 (Bidirectio  (None, 32)               3456      
 nal)                                                            
                                                                 
 dense_1 (Dense)             (None, 9421)              310893    
                                                                 
Total params: 408,559
Trainable params: 408,559
Non-trainable params: 0
_________________________________________________________________


In [ ]:
h = model.fit(x_train, y_train, epochs=20)